/** This program is a part of mudcore
 *-----------------------------------------
 * File   : stdob.h
 * Author : 由 creator 產生
 * Note   : Include File.
 *-----------------------------------------
 */
#define STD_CHURCH                               "/std/room/church.c"
#define STD_DUNGEON                              "/std/room/dungeon.c"
#define STD_DUNGEON_8                            "/std/room/dungeon_8.c"
#define STD_DUNGEON_9                            "/std/room/dungeon_9.c"
#define STD_INN                                  "/std/room/inn.c"
#define STD_OUTDOORS                             "/std/room/outdoors.c"
#define STD_ROOM                                 "/std/room/room.c"
#define STD_WILD                                 "/std/room/wild.c"
#define STD_WILD_8                               "/std/room/wild_8.c"
#define STD_WILD_9                               "/std/room/wild_9.c"
#define STD_DEALER                               "/std/living/dealer.c"
#define STD_DIVINE                               "/std/living/divine.c"
#define STD_EQUIPMENT_DEALER                     "/std/living/equipment_dealer.c"
#define STD_ITEM_DEALER                          "/std/living/item_dealer.c"
#define STD_MAID                                 "/std/living/maid.c"
#define STD_MOB                                  "/std/living/mob.c"
#define STD_NPC                                  "/std/living/npc.c"
#define STD_QUESTER                              "/std/living/quester.c"
#define STD_ACCESSORY                            "/std/equipment/accessory.c"
#define STD_ARMOR                                "/std/equipment/armour/armor.c"
#define STD_BRACER                               "/std/equipment/armour/bracer.c"
#define STD_HELMET                               "/std/equipment/armour/helmet.c"
#define STD_SHIELD                               "/std/equipment/armour/shield.c"
#define STD_SHOE                                 "/std/equipment/armour/shoe.c"
#define STD_TROUSER                              "/std/equipment/armour/trouser.c"
#define STD_ARMOUR                               "/std/equipment/armour.c"
#define STD_EQUIPMENT                            "/std/equipment/equipment.c"
#define STD_AXE                                  "/std/equipment/weapon/axe.c"
#define STD_BOOMERANG                            "/std/equipment/weapon/boomerang.c"
#define STD_BOW                                  "/std/equipment/weapon/bow.c"
#define STD_CLAW                                 "/std/equipment/weapon/claw.c"
#define STD_FAN                                  "/std/equipment/weapon/fan.c"
#define STD_HAMMER                               "/std/equipment/weapon/hammer.c"
#define STD_KNIFE                                "/std/equipment/weapon/knife.c"
#define STD_SPEAR                                "/std/equipment/weapon/spear.c"
#define STD_STAFF                                "/std/equipment/weapon/staff.c"
#define STD_SWORD                                "/std/equipment/weapon/sword.c"
#define STD_WAND                                 "/std/equipment/weapon/wand.c"
#define STD_WHIP                                 "/std/equipment/weapon/whip.c"
#define STD_WEAPON                               "/std/equipment/weapon.c"
#define STD_ALCHEMY                              "/std/item/alchemy.c"
#define STD_GIFT                                 "/std/item/gift.c"
#define STD_ITEM                                 "/std/item/item.c"
#define STD_MAGIC                                "/std/item/magic.c"
#define STD_MEDICINE                             "/std/item/medicine.c"
